### PR TITLE
Daemonize container

### PR DESCRIPTION
**Pull request by kktuax**
In order to be able to start and stop database in container automatically

### CODE REVIEW

**Comment by 0x1fff** [comment]
Hi thank you for pull request :). 

As far as I remember Informix Dynamic Server is started by simple bash script when container is created. I don't know supervisord and daemonizer software, what problems it solves, what problems it creates?

For the rest of your commits, I'll try to explain why I haven't done it the way you changed it, and why I will reject your pull request:
1. wget is used to create only one intermediate container when building docker-informix image; each usage of copy command in Dockerfile creates intermediate image with snapshot of full file system state; Informix package (tar.gz) is about 450MB so this 450 MB will be added to image permanently (even it will be deleted) and users using this container will have to download it and won't be able to use it later, so I'm not using COPY command on purpose.
2. If you put your informix*.tar.gz file and rest of files in directory where is Dockerfile, it will be copied when building Docker container it will be sent to docker builder (see Docker Context [docs](https://docs.docker.com/reference/builder/), [Info about uploading context](https://github.com/docker/docker/issues/2342))
3. I see that you've also added Java 7 Platform from Oracle into dependencies to be able to use supervisord and daemonizer from your own repository in commit: e8022671251513e999cac16845bea2acd6c687ef, is this correct? 

```
## Download daemonizer tool
wget https://raw.githubusercontent.com/Predictia/maven-repo/master/releases/es/predictia/daemonizer/XXXXXXXX -O daemonizer.jar
```

**Sorry, I don't trust something that is not official from official repository, and there is no source code available.**

**Comment by kktuax** [comment]
Maybe I shoud have taken more time to explain the changes. Daemonizer source code can be found here: https://github.com/Predictia/daemonizer. Basically it executes a command, sleeps forever and when terminated executes another command (see [Daemon.java](https://github.com/Predictia/daemonizer/blob/master/src/main/java/es/predictia/daemonizer/Daemon.java)). About point 3, yes, Java7 is added just to be able to run this program. 

We are trying to allow the container to start the informix service in daemon mode, without executing any further commands attaching to the container. Supervisor starts a process (in this case daemonizer) and when the container is terminated, propagates the sigkill to the daemon, that will try to shutdown the database. This way we can issue a "docker restart informix" and will gracefully restart.

About the reason for not using the COPY command, it seemed a bit obscure but you are right: it's more space-efficient if you don't create many steps in the Dockerfile. In case you want to slim down the container after the build process we could use [this approach](http://stackoverflow.com/questions/22713551/how-to-flatten-a-docker-image).

**Comment by 0x1fff** [comment]
Hi!

Thank you for your explanation about daemonizer and supervisor. I've checked out the [supervisor project webpage](http://supervisord.org/) and source of daemonizer.

After reading you message I think the root problem that you are trying to solve is that the container didn't shutdown gracefully when users were connected to database is this right? 

After checking out [Informix Dynamic Server docs](http://www-01.ibm.com/support/knowledgecenter/SSGU8G_11.50.0/com.ibm.adref.doc/ids_adr_0422.htm) I've found out that there are few ways to shutdown Informix. I was using command which waits for users to disconnect - it was wrong on your use case. In commit b0fc51e36e50e39e5ef3dc021823aa9a61eb6610 I've changed shutdown to force rollback any pending transactions and force disconnect clients.

I think it will solve your problem - could you check it? I have tried using: docker start xxx ; docker stop xxx; docker start xxx; docker restart xxx; and my container exited cleanly.

I didn't plan to use the supervisor because in container is running only one process. Informix has it own tools to manage database state (which are not perfect) :(. When I will expand container with other services I definitely will use supervisor.

About COPY and flatten a Docker image approach it is very good for containers created from scratch - because you don't have to download the base image - if you flatten it you will have to download Debian image again, but you won't be able to track from which Debian container version it was created. 

I'm sorry for such a long message, but I would like to make this container small with as few dependencies as possible.

**Comment by kktuax** [comment]
Thank you for taking the time to investigate how to properly force shutdown, yes that was the case. 

About process management, the usual case in docker is running single processes services in foreground,  this way signals are properly routed on stop in order to gracefully shutdown. In our case, informix manages several processes (actually in our fork supervisord complains about unknown processes being started), so makes sense to use the "informix way" of shutting them down. In your case you are using bash to propagate the signals, which makes sense because it doesn't add additional dependencies. You can keep this PR closed.

**Comment by 0x1fff** [comment]
I'm glad that I could help you and my changes solved your problem :D :). 

I didn't found in Informix documentation option to run oninit in foreground to easily dockerize it. 
So I choose to run shell in docker container, so I can attach to it container and run some administrative tasks from command line - not everything is possible from SQL :(. Command line interface is also very helpful to gather Informix statistics about database engine.

This docker container currently runs almost on default settings, it means you have to manage [dbspaces, logical logs and other stuff by yourself](http://www.informix-dba.com/2010/07/creating-dbspaces-databases-tables-and.html) - there is only a small dbspace and few logical logs created - it should be good for development, not for heavy usage. You should also consider [tuning I/O](http://www.informix-dba.com/2010/07/increasing-buffers-and-reducing-io-with.html). 

If you tune your Informix Dynamic Server installation to be more autonomous than is today I would be very interested to merge your changes in configuration files to this repository :).

**Pull request closed without merging**
